services:
  postgres1:
    image: postgres:latest
    container_name: postgres_test_1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - test_network

  postgres2:
    image: postgres:latest
    container_name: postgres_test_2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15433:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - test_network

volumes:
  postgres1_data:
  postgres2_data:

networks:
  test_network:
    driver: bridge
