[project]
name = "test-db"
version = "0.1.0"
description = "PostgreSQL 17 Master-Slave replication test environment"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "psycopg2-binary==2.9.9",
]
